services:
- type: web
  name: transcriber
  runtime: docker
  repo: https://github.com/vasiliadi/transcriber
  plan: free
  envVars:
  - key: REPLICATE_API_TOKEN
    sync: false
  - key: GEMINI_API_KEY
    sync: false
  - key: HF_ACCESS_TOKEN
    sync: false
  - key: ELEVENLABS_API_KEY
    sync: false
  region: oregon
  healthCheckPath: /_stcore/health
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
